// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmesh/booking/ent/auth"
	"github.com/openmesh/booking/ent/predicate"
	"github.com/openmesh/booking/ent/user"
)

// AuthUpdate is the builder for updating Auth entities.
type AuthUpdate struct {
	config
	hooks    []Hook
	mutation *AuthMutation
}

// Where appends a list predicates to the AuthUpdate builder.
func (au *AuthUpdate) Where(ps ...predicate.Auth) *AuthUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdatedAt sets the "updatedAt" field.
func (au *AuthUpdate) SetUpdatedAt(t time.Time) *AuthUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetSource sets the "source" field.
func (au *AuthUpdate) SetSource(s string) *AuthUpdate {
	au.mutation.SetSource(s)
	return au
}

// SetSourceId sets the "sourceId" field.
func (au *AuthUpdate) SetSourceId(s string) *AuthUpdate {
	au.mutation.SetSourceId(s)
	return au
}

// SetAccessToken sets the "accessToken" field.
func (au *AuthUpdate) SetAccessToken(s string) *AuthUpdate {
	au.mutation.SetAccessToken(s)
	return au
}

// SetNillableAccessToken sets the "accessToken" field if the given value is not nil.
func (au *AuthUpdate) SetNillableAccessToken(s *string) *AuthUpdate {
	if s != nil {
		au.SetAccessToken(*s)
	}
	return au
}

// ClearAccessToken clears the value of the "accessToken" field.
func (au *AuthUpdate) ClearAccessToken() *AuthUpdate {
	au.mutation.ClearAccessToken()
	return au
}

// SetRefreshToken sets the "refreshToken" field.
func (au *AuthUpdate) SetRefreshToken(s string) *AuthUpdate {
	au.mutation.SetRefreshToken(s)
	return au
}

// SetNillableRefreshToken sets the "refreshToken" field if the given value is not nil.
func (au *AuthUpdate) SetNillableRefreshToken(s *string) *AuthUpdate {
	if s != nil {
		au.SetRefreshToken(*s)
	}
	return au
}

// ClearRefreshToken clears the value of the "refreshToken" field.
func (au *AuthUpdate) ClearRefreshToken() *AuthUpdate {
	au.mutation.ClearRefreshToken()
	return au
}

// SetExpiry sets the "expiry" field.
func (au *AuthUpdate) SetExpiry(t time.Time) *AuthUpdate {
	au.mutation.SetExpiry(t)
	return au
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (au *AuthUpdate) SetNillableExpiry(t *time.Time) *AuthUpdate {
	if t != nil {
		au.SetExpiry(*t)
	}
	return au
}

// ClearExpiry clears the value of the "expiry" field.
func (au *AuthUpdate) ClearExpiry() *AuthUpdate {
	au.mutation.ClearExpiry()
	return au
}

// SetUserId sets the "userId" field.
func (au *AuthUpdate) SetUserId(i int) *AuthUpdate {
	au.mutation.SetUserId(i)
	return au
}

// SetUserID sets the "user" edge to the User entity by ID.
func (au *AuthUpdate) SetUserID(id int) *AuthUpdate {
	au.mutation.SetUserID(id)
	return au
}

// SetUser sets the "user" edge to the User entity.
func (au *AuthUpdate) SetUser(u *User) *AuthUpdate {
	return au.SetUserID(u.ID)
}

// Mutation returns the AuthMutation object of the builder.
func (au *AuthUpdate) Mutation() *AuthMutation {
	return au.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (au *AuthUpdate) ClearUser() *AuthUpdate {
	au.mutation.ClearUser()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AuthUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	au.defaults()
	if len(au.hooks) == 0 {
		if err = au.check(); err != nil {
			return 0, err
		}
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = au.check(); err != nil {
				return 0, err
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AuthUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AuthUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AuthUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AuthUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := auth.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AuthUpdate) check() error {
	if _, ok := au.mutation.UserID(); au.mutation.UserCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"user\"")
	}
	return nil
}

func (au *AuthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   auth.Table,
			Columns: auth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: auth.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: auth.FieldUpdatedAt,
		})
	}
	if value, ok := au.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldSource,
		})
	}
	if value, ok := au.mutation.SourceId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldSourceId,
		})
	}
	if value, ok := au.mutation.AccessToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldAccessToken,
		})
	}
	if au.mutation.AccessTokenCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: auth.FieldAccessToken,
		})
	}
	if value, ok := au.mutation.RefreshToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldRefreshToken,
		})
	}
	if au.mutation.RefreshTokenCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: auth.FieldRefreshToken,
		})
	}
	if value, ok := au.mutation.Expiry(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: auth.FieldExpiry,
		})
	}
	if au.mutation.ExpiryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: auth.FieldExpiry,
		})
	}
	if au.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auth.UserTable,
			Columns: []string{auth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auth.UserTable,
			Columns: []string{auth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AuthUpdateOne is the builder for updating a single Auth entity.
type AuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthMutation
}

// SetUpdatedAt sets the "updatedAt" field.
func (auo *AuthUpdateOne) SetUpdatedAt(t time.Time) *AuthUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetSource sets the "source" field.
func (auo *AuthUpdateOne) SetSource(s string) *AuthUpdateOne {
	auo.mutation.SetSource(s)
	return auo
}

// SetSourceId sets the "sourceId" field.
func (auo *AuthUpdateOne) SetSourceId(s string) *AuthUpdateOne {
	auo.mutation.SetSourceId(s)
	return auo
}

// SetAccessToken sets the "accessToken" field.
func (auo *AuthUpdateOne) SetAccessToken(s string) *AuthUpdateOne {
	auo.mutation.SetAccessToken(s)
	return auo
}

// SetNillableAccessToken sets the "accessToken" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableAccessToken(s *string) *AuthUpdateOne {
	if s != nil {
		auo.SetAccessToken(*s)
	}
	return auo
}

// ClearAccessToken clears the value of the "accessToken" field.
func (auo *AuthUpdateOne) ClearAccessToken() *AuthUpdateOne {
	auo.mutation.ClearAccessToken()
	return auo
}

// SetRefreshToken sets the "refreshToken" field.
func (auo *AuthUpdateOne) SetRefreshToken(s string) *AuthUpdateOne {
	auo.mutation.SetRefreshToken(s)
	return auo
}

// SetNillableRefreshToken sets the "refreshToken" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableRefreshToken(s *string) *AuthUpdateOne {
	if s != nil {
		auo.SetRefreshToken(*s)
	}
	return auo
}

// ClearRefreshToken clears the value of the "refreshToken" field.
func (auo *AuthUpdateOne) ClearRefreshToken() *AuthUpdateOne {
	auo.mutation.ClearRefreshToken()
	return auo
}

// SetExpiry sets the "expiry" field.
func (auo *AuthUpdateOne) SetExpiry(t time.Time) *AuthUpdateOne {
	auo.mutation.SetExpiry(t)
	return auo
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (auo *AuthUpdateOne) SetNillableExpiry(t *time.Time) *AuthUpdateOne {
	if t != nil {
		auo.SetExpiry(*t)
	}
	return auo
}

// ClearExpiry clears the value of the "expiry" field.
func (auo *AuthUpdateOne) ClearExpiry() *AuthUpdateOne {
	auo.mutation.ClearExpiry()
	return auo
}

// SetUserId sets the "userId" field.
func (auo *AuthUpdateOne) SetUserId(i int) *AuthUpdateOne {
	auo.mutation.SetUserId(i)
	return auo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (auo *AuthUpdateOne) SetUserID(id int) *AuthUpdateOne {
	auo.mutation.SetUserID(id)
	return auo
}

// SetUser sets the "user" edge to the User entity.
func (auo *AuthUpdateOne) SetUser(u *User) *AuthUpdateOne {
	return auo.SetUserID(u.ID)
}

// Mutation returns the AuthMutation object of the builder.
func (auo *AuthUpdateOne) Mutation() *AuthMutation {
	return auo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (auo *AuthUpdateOne) ClearUser() *AuthUpdateOne {
	auo.mutation.ClearUser()
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AuthUpdateOne) Select(field string, fields ...string) *AuthUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Auth entity.
func (auo *AuthUpdateOne) Save(ctx context.Context) (*Auth, error) {
	var (
		err  error
		node *Auth
	)
	auo.defaults()
	if len(auo.hooks) == 0 {
		if err = auo.check(); err != nil {
			return nil, err
		}
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = auo.check(); err != nil {
				return nil, err
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AuthUpdateOne) SaveX(ctx context.Context) *Auth {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AuthUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AuthUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AuthUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := auth.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AuthUpdateOne) check() error {
	if _, ok := auo.mutation.UserID(); auo.mutation.UserCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"user\"")
	}
	return nil
}

func (auo *AuthUpdateOne) sqlSave(ctx context.Context) (_node *Auth, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   auth.Table,
			Columns: auth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: auth.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Auth.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auth.FieldID)
		for _, f := range fields {
			if !auth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: auth.FieldUpdatedAt,
		})
	}
	if value, ok := auo.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldSource,
		})
	}
	if value, ok := auo.mutation.SourceId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldSourceId,
		})
	}
	if value, ok := auo.mutation.AccessToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldAccessToken,
		})
	}
	if auo.mutation.AccessTokenCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: auth.FieldAccessToken,
		})
	}
	if value, ok := auo.mutation.RefreshToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: auth.FieldRefreshToken,
		})
	}
	if auo.mutation.RefreshTokenCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: auth.FieldRefreshToken,
		})
	}
	if value, ok := auo.mutation.Expiry(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: auth.FieldExpiry,
		})
	}
	if auo.mutation.ExpiryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: auth.FieldExpiry,
		})
	}
	if auo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auth.UserTable,
			Columns: []string{auth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   auth.UserTable,
			Columns: []string{auth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Auth{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
