// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/openmesh/booking/ent/organization"
	"github.com/openmesh/booking/ent/organizationownership"
	"github.com/openmesh/booking/ent/predicate"
	"github.com/openmesh/booking/ent/user"
)

// OrganizationOwnershipQuery is the builder for querying OrganizationOwnership entities.
type OrganizationOwnershipQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OrganizationOwnership
	// eager-loading edges.
	withUser         *UserQuery
	withOrganization *OrganizationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrganizationOwnershipQuery builder.
func (ooq *OrganizationOwnershipQuery) Where(ps ...predicate.OrganizationOwnership) *OrganizationOwnershipQuery {
	ooq.predicates = append(ooq.predicates, ps...)
	return ooq
}

// Limit adds a limit step to the query.
func (ooq *OrganizationOwnershipQuery) Limit(limit int) *OrganizationOwnershipQuery {
	ooq.limit = &limit
	return ooq
}

// Offset adds an offset step to the query.
func (ooq *OrganizationOwnershipQuery) Offset(offset int) *OrganizationOwnershipQuery {
	ooq.offset = &offset
	return ooq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ooq *OrganizationOwnershipQuery) Unique(unique bool) *OrganizationOwnershipQuery {
	ooq.unique = &unique
	return ooq
}

// Order adds an order step to the query.
func (ooq *OrganizationOwnershipQuery) Order(o ...OrderFunc) *OrganizationOwnershipQuery {
	ooq.order = append(ooq.order, o...)
	return ooq
}

// QueryUser chains the current query on the "user" edge.
func (ooq *OrganizationOwnershipQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: ooq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ooq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ooq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(organizationownership.Table, organizationownership.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, organizationownership.UserTable, organizationownership.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ooq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganization chains the current query on the "organization" edge.
func (ooq *OrganizationOwnershipQuery) QueryOrganization() *OrganizationQuery {
	query := &OrganizationQuery{config: ooq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ooq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ooq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(organizationownership.Table, organizationownership.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, organizationownership.OrganizationTable, organizationownership.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(ooq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrganizationOwnership entity from the query.
// Returns a *NotFoundError when no OrganizationOwnership was found.
func (ooq *OrganizationOwnershipQuery) First(ctx context.Context) (*OrganizationOwnership, error) {
	nodes, err := ooq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{organizationownership.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) FirstX(ctx context.Context) *OrganizationOwnership {
	node, err := ooq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrganizationOwnership ID from the query.
// Returns a *NotFoundError when no OrganizationOwnership ID was found.
func (ooq *OrganizationOwnershipQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ooq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{organizationownership.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) FirstIDX(ctx context.Context) int {
	id, err := ooq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrganizationOwnership entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one OrganizationOwnership entity is not found.
// Returns a *NotFoundError when no OrganizationOwnership entities are found.
func (ooq *OrganizationOwnershipQuery) Only(ctx context.Context) (*OrganizationOwnership, error) {
	nodes, err := ooq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{organizationownership.Label}
	default:
		return nil, &NotSingularError{organizationownership.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) OnlyX(ctx context.Context) *OrganizationOwnership {
	node, err := ooq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrganizationOwnership ID in the query.
// Returns a *NotSingularError when exactly one OrganizationOwnership ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ooq *OrganizationOwnershipQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ooq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = &NotSingularError{organizationownership.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) OnlyIDX(ctx context.Context) int {
	id, err := ooq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrganizationOwnerships.
func (ooq *OrganizationOwnershipQuery) All(ctx context.Context) ([]*OrganizationOwnership, error) {
	if err := ooq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ooq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) AllX(ctx context.Context) []*OrganizationOwnership {
	nodes, err := ooq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrganizationOwnership IDs.
func (ooq *OrganizationOwnershipQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ooq.Select(organizationownership.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) IDsX(ctx context.Context) []int {
	ids, err := ooq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ooq *OrganizationOwnershipQuery) Count(ctx context.Context) (int, error) {
	if err := ooq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ooq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) CountX(ctx context.Context) int {
	count, err := ooq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ooq *OrganizationOwnershipQuery) Exist(ctx context.Context) (bool, error) {
	if err := ooq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ooq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ooq *OrganizationOwnershipQuery) ExistX(ctx context.Context) bool {
	exist, err := ooq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrganizationOwnershipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ooq *OrganizationOwnershipQuery) Clone() *OrganizationOwnershipQuery {
	if ooq == nil {
		return nil
	}
	return &OrganizationOwnershipQuery{
		config:           ooq.config,
		limit:            ooq.limit,
		offset:           ooq.offset,
		order:            append([]OrderFunc{}, ooq.order...),
		predicates:       append([]predicate.OrganizationOwnership{}, ooq.predicates...),
		withUser:         ooq.withUser.Clone(),
		withOrganization: ooq.withOrganization.Clone(),
		// clone intermediate query.
		sql:  ooq.sql.Clone(),
		path: ooq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ooq *OrganizationOwnershipQuery) WithUser(opts ...func(*UserQuery)) *OrganizationOwnershipQuery {
	query := &UserQuery{config: ooq.config}
	for _, opt := range opts {
		opt(query)
	}
	ooq.withUser = query
	return ooq
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (ooq *OrganizationOwnershipQuery) WithOrganization(opts ...func(*OrganizationQuery)) *OrganizationOwnershipQuery {
	query := &OrganizationQuery{config: ooq.config}
	for _, opt := range opts {
		opt(query)
	}
	ooq.withOrganization = query
	return ooq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserId int `json:"userId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrganizationOwnership.Query().
//		GroupBy(organizationownership.FieldUserId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ooq *OrganizationOwnershipQuery) GroupBy(field string, fields ...string) *OrganizationOwnershipGroupBy {
	group := &OrganizationOwnershipGroupBy{config: ooq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ooq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ooq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserId int `json:"userId,omitempty"`
//	}
//
//	client.OrganizationOwnership.Query().
//		Select(organizationownership.FieldUserId).
//		Scan(ctx, &v)
//
func (ooq *OrganizationOwnershipQuery) Select(fields ...string) *OrganizationOwnershipSelect {
	ooq.fields = append(ooq.fields, fields...)
	return &OrganizationOwnershipSelect{OrganizationOwnershipQuery: ooq}
}

func (ooq *OrganizationOwnershipQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ooq.fields {
		if !organizationownership.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ooq.path != nil {
		prev, err := ooq.path(ctx)
		if err != nil {
			return err
		}
		ooq.sql = prev
	}
	return nil
}

func (ooq *OrganizationOwnershipQuery) sqlAll(ctx context.Context) ([]*OrganizationOwnership, error) {
	var (
		nodes       = []*OrganizationOwnership{}
		_spec       = ooq.querySpec()
		loadedTypes = [2]bool{
			ooq.withUser != nil,
			ooq.withOrganization != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &OrganizationOwnership{config: ooq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ooq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := ooq.withUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*OrganizationOwnership)
		for i := range nodes {
			fk := nodes[i].UserId
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "userId" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	if query := ooq.withOrganization; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*OrganizationOwnership)
		for i := range nodes {
			fk := nodes[i].OrganizationId
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(organization.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "organizationId" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Organization = n
			}
		}
	}

	return nodes, nil
}

func (ooq *OrganizationOwnershipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ooq.querySpec()
	return sqlgraph.CountNodes(ctx, ooq.driver, _spec)
}

func (ooq *OrganizationOwnershipQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ooq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ooq *OrganizationOwnershipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   organizationownership.Table,
			Columns: organizationownership.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: organizationownership.FieldID,
			},
		},
		From:   ooq.sql,
		Unique: true,
	}
	if unique := ooq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ooq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationownership.FieldID)
		for i := range fields {
			if fields[i] != organizationownership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ooq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ooq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ooq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ooq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ooq *OrganizationOwnershipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ooq.driver.Dialect())
	t1 := builder.Table(organizationownership.Table)
	columns := ooq.fields
	if len(columns) == 0 {
		columns = organizationownership.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ooq.sql != nil {
		selector = ooq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ooq.predicates {
		p(selector)
	}
	for _, p := range ooq.order {
		p(selector)
	}
	if offset := ooq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ooq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrganizationOwnershipGroupBy is the group-by builder for OrganizationOwnership entities.
type OrganizationOwnershipGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oogb *OrganizationOwnershipGroupBy) Aggregate(fns ...AggregateFunc) *OrganizationOwnershipGroupBy {
	oogb.fns = append(oogb.fns, fns...)
	return oogb
}

// Scan applies the group-by query and scans the result into the given value.
func (oogb *OrganizationOwnershipGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := oogb.path(ctx)
	if err != nil {
		return err
	}
	oogb.sql = query
	return oogb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := oogb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(oogb.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := oogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) StringsX(ctx context.Context) []string {
	v, err := oogb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = oogb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) StringX(ctx context.Context) string {
	v, err := oogb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(oogb.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := oogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) IntsX(ctx context.Context) []int {
	v, err := oogb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = oogb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) IntX(ctx context.Context) int {
	v, err := oogb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(oogb.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := oogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := oogb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = oogb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) Float64X(ctx context.Context) float64 {
	v, err := oogb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(oogb.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := oogb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := oogb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (oogb *OrganizationOwnershipGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = oogb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (oogb *OrganizationOwnershipGroupBy) BoolX(ctx context.Context) bool {
	v, err := oogb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (oogb *OrganizationOwnershipGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range oogb.fields {
		if !organizationownership.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := oogb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oogb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (oogb *OrganizationOwnershipGroupBy) sqlQuery() *sql.Selector {
	selector := oogb.sql.Select()
	aggregation := make([]string, 0, len(oogb.fns))
	for _, fn := range oogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(oogb.fields)+len(oogb.fns))
		for _, f := range oogb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(oogb.fields...)...)
}

// OrganizationOwnershipSelect is the builder for selecting fields of OrganizationOwnership entities.
type OrganizationOwnershipSelect struct {
	*OrganizationOwnershipQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (oos *OrganizationOwnershipSelect) Scan(ctx context.Context, v interface{}) error {
	if err := oos.prepareQuery(ctx); err != nil {
		return err
	}
	oos.sql = oos.OrganizationOwnershipQuery.sqlQuery(ctx)
	return oos.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) ScanX(ctx context.Context, v interface{}) {
	if err := oos.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Strings(ctx context.Context) ([]string, error) {
	if len(oos.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := oos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) StringsX(ctx context.Context) []string {
	v, err := oos.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = oos.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) StringX(ctx context.Context) string {
	v, err := oos.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Ints(ctx context.Context) ([]int, error) {
	if len(oos.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := oos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) IntsX(ctx context.Context) []int {
	v, err := oos.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = oos.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) IntX(ctx context.Context) int {
	v, err := oos.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(oos.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := oos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) Float64sX(ctx context.Context) []float64 {
	v, err := oos.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = oos.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) Float64X(ctx context.Context) float64 {
	v, err := oos.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(oos.fields) > 1 {
		return nil, errors.New("ent: OrganizationOwnershipSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := oos.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) BoolsX(ctx context.Context) []bool {
	v, err := oos.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (oos *OrganizationOwnershipSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = oos.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{organizationownership.Label}
	default:
		err = fmt.Errorf("ent: OrganizationOwnershipSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (oos *OrganizationOwnershipSelect) BoolX(ctx context.Context) bool {
	v, err := oos.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (oos *OrganizationOwnershipSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := oos.sql.Query()
	if err := oos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
