// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// BookingMetadatum is the predicate function for bookingmetadatum builders.
type BookingMetadatum func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationOwnership is the predicate function for organizationownership builders.
type OrganizationOwnership func(*sql.Selector)

// Resource is the predicate function for resource builders.
type Resource func(*sql.Selector)

// Slot is the predicate function for slot builders.
type Slot func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// Unavailability is the predicate function for unavailability builders.
type Unavailability func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
